contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #pacvario channel"
    url: https://nfcore.slack.com/channels/pacvario
    about: Discussion about the nf-core/pacvario pipeline
